/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package design;

import bean.Db_connection;
import bean.ObjDao;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.border.LineBorder;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Java Developer
 */
public class AdminFrame extends javax.swing.JFrame {
    
    private final DateFormat df = new SimpleDateFormat("yyy-MM-dd");
    String registration_date= (df.format(new Date()));
   
     public void Getdata()   //for retriving value of user details
     {
         try
	 {
             Connection con=Db_connection.getConnection();
             PreparedStatement ps;               
             ps= con.prepareStatement("select * from user");
             ResultSet rs = ps.executeQuery();
	     int i = 0;
	     String si = null;
	     DefaultTableModel model = null;
	     model = (DefaultTableModel) UserDetalis.getModel();
             while (rs.next())
	     {
		int atype = rs.getInt(3);
		//System.out.println(si);
		switch(atype)
		{
                case 1:
                    si = "Administrator";
                    break; 
		case 2:
                    si = "Food Shop Manager";
                    break;
		case 3:
                    si = "Off Shop Manager";
                    break; 
		case 4:
                    si = "On Shop Manager";
                    break;
		}
		model.insertRow(i , new Object[]{rs.getString(1), rs.getString(4), rs.getString(5), si});
		i++;
	     }
	     ps.close();
	     con.close();
	     //System.out.println(model.getRowCount());
	 }
          catch( Exception e)
          {
          e.printStackTrace();
          }
     }                                      //end
                                           //for retriving value of user details

        int h, w;
    
    public AdminFrame(String s) {
        initComponents();
        
        //ObjDao.af=this;
        
        jLabel10.setText(s);
	Toolkit t = Toolkit.getDefaultToolkit();
        Dimension d = t.getScreenSize();
        h = d.height;
        w = d.width;
	this.setSize( w , h );
        
	//jPanel5.setVisible(false);     
	jPanel4.setVisible(false);// new uswr panel
	//jPanel11.setVisible(false);//transport pass
	//offshopPanel.setVisible(false);//off shop shell
	this.setExtendedState(this.MAXIMIZED_BOTH);
     
	//WineStockPanel.setVisible(false);
	UserDetalis.setShowGrid(true);
        UserDetalis.setShowHorizontalLines(true);
        UserDetalis.setShowVerticalLines(true);
        UserDetalis.setFillsViewportHeight(true);
        DefaultTableCellRenderer headerRenderer = new DefaultTableCellRenderer();
        headerRenderer.setBackground(new Color(255,255,255));
        UserDetalis.getTableHeader().setBorder(new LineBorder(Color.black, 1));
	UserDetalis.getTableHeader().setPreferredSize(new Dimension(jScrollPane4.getWidth(),35));
        Getdata();
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        reportsPopUp = new javax.swing.JPopupMenu(){
            @Override
            public void paintComponent(final Graphics g) {
                g.setColor(new Color(0,82,72,150));
                g.fillRect(0,0,getWidth(), getHeight());
            }
        };
        tPassReports = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        mainStockReports = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        sellStockReports = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        cashColReports = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        sellsReports = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        new_user = new javax.swing.JButton();
        Main_Stock = new javax.swing.JButton();
        tPassEntry = new javax.swing.JButton();
        FoodEntry = new javax.swing.JButton();
        newDrinksCat = new javax.swing.JButton();
        maintoShop = new javax.swing.JButton();
        setPrice = new javax.swing.JButton();
        config = new javax.swing.JButton();
        reports = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        Phone_no = new javax.swing.JTextField();
        delete = new javax.swing.JButton();
        update = new javax.swing.JButton();
        add = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        Password = new javax.swing.JPasswordField();
        jScrollPane4 = new javax.swing.JScrollPane();
        UserDetalis = new javax.swing.JTable();
        jComboBox7 = new javax.swing.JComboBox<>();
        jLabel62 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField39 = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();

        reportsPopUp.setOpaque(false);
        reportsPopUp.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N

        reportsPopUp.setForeground(new java.awt.Color(255, 255, 255));
        reportsPopUp.setBackground(new java.awt.Color(255, 255, 255));
        reportsPopUp.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        reportsPopUp.setForeground(new java.awt.Color(255, 255, 255));

        tPassReports.setBackground(new java.awt.Color(255, 255, 255));
        tPassReports.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        tPassReports.setForeground(new java.awt.Color(255, 255, 255));
        tPassReports.setText("1. Transport Pass Reports");
        tPassReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tPassReportsActionPerformed(evt);
            }
        });
        reportsPopUp.add(tPassReports);
        reportsPopUp.add(jSeparator3);

        mainStockReports.setBackground(new java.awt.Color(255, 255, 255));
        mainStockReports.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        mainStockReports.setForeground(new java.awt.Color(255, 255, 255));
        mainStockReports.setText("2. Main Stock Reports");
        mainStockReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainStockReportsActionPerformed(evt);
            }
        });
        reportsPopUp.add(mainStockReports);
        reportsPopUp.add(jSeparator4);

        sellStockReports.setBackground(new java.awt.Color(255, 255, 255));
        sellStockReports.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        sellStockReports.setForeground(new java.awt.Color(255, 255, 255));
        sellStockReports.setText("3. Sells Stock Reports");
        sellStockReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sellStockReportsActionPerformed(evt);
            }
        });
        reportsPopUp.add(sellStockReports);
        reportsPopUp.add(jSeparator5);

        cashColReports.setBackground(new java.awt.Color(255, 255, 255));
        cashColReports.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        cashColReports.setForeground(new java.awt.Color(255, 255, 255));
        cashColReports.setText("4. Cash Collection Reports");
        cashColReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashColReportsActionPerformed(evt);
            }
        });
        reportsPopUp.add(cashColReports);
        reportsPopUp.add(jSeparator6);

        sellsReports.setBackground(new java.awt.Color(255, 255, 255));
        sellsReports.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        sellsReports.setForeground(new java.awt.Color(255, 255, 255));
        sellsReports.setText("5. Sell Reports");
        sellsReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sellsReportsActionPerformed(evt);
            }
        });
        reportsPopUp.add(sellsReports);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Wine Shop Management System");
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jLabel10.setBackground(new java.awt.Color(0, 0, 0));
        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("User");

        jLabel63.setBackground(new java.awt.Color(0, 0, 0));
        jLabel63.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel63.setForeground(new java.awt.Color(255, 255, 255));
        jLabel63.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel63.setText("               ADMINISTRATOR");

        jLabel64.setBackground(new java.awt.Color(0, 0, 0));
        jLabel64.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel64.setForeground(new java.awt.Color(255, 255, 255));
        jLabel64.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel64.setText("Welcome");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel63, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel64)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel63, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
            .addComponent(jLabel64, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        new_user.setBackground(new java.awt.Color(0, 0, 0));
        new_user.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        new_user.setForeground(new java.awt.Color(255, 255, 255));
        new_user.setText("Create New User");
        new_user.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                new_userMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                new_userMouseExited(evt);
            }
        });
        new_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new_userActionPerformed(evt);
            }
        });

        Main_Stock.setBackground(new java.awt.Color(0, 0, 0));
        Main_Stock.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Main_Stock.setForeground(new java.awt.Color(255, 255, 255));
        Main_Stock.setText("Main Stock Entry");
        Main_Stock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Main_StockMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Main_StockMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Main_StockMouseExited(evt);
            }
        });
        Main_Stock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Main_StockActionPerformed(evt);
            }
        });

        tPassEntry.setBackground(new java.awt.Color(0, 0, 0));
        tPassEntry.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        tPassEntry.setForeground(new java.awt.Color(255, 255, 255));
        tPassEntry.setText("Transport Pass Entry");
        tPassEntry.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tPassEntryMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tPassEntryMouseExited(evt);
            }
        });
        tPassEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tPassEntryActionPerformed(evt);
            }
        });

        FoodEntry.setBackground(new java.awt.Color(0, 0, 0));
        FoodEntry.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        FoodEntry.setForeground(new java.awt.Color(255, 255, 255));
        FoodEntry.setText("New Food Category");
        FoodEntry.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FoodEntryMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                FoodEntryMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                FoodEntryMouseExited(evt);
            }
        });
        FoodEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FoodEntryActionPerformed(evt);
            }
        });

        newDrinksCat.setBackground(new java.awt.Color(0, 0, 0));
        newDrinksCat.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        newDrinksCat.setForeground(new java.awt.Color(255, 255, 255));
        newDrinksCat.setText("New Drinks Category");
        newDrinksCat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newDrinksCatMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                newDrinksCatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                newDrinksCatMouseExited(evt);
            }
        });
        newDrinksCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newDrinksCatActionPerformed(evt);
            }
        });

        maintoShop.setBackground(new java.awt.Color(0, 0, 0));
        maintoShop.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        maintoShop.setForeground(new java.awt.Color(255, 255, 255));
        maintoShop.setText("Wine Distribution");
        maintoShop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                maintoShopMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                maintoShopMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                maintoShopMouseExited(evt);
            }
        });
        maintoShop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maintoShopActionPerformed(evt);
            }
        });

        setPrice.setBackground(new java.awt.Color(0, 0, 0));
        setPrice.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        setPrice.setForeground(new java.awt.Color(255, 255, 255));
        setPrice.setText("On Shop Price Set");
        setPrice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                setPriceMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                setPriceMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                setPriceMouseExited(evt);
            }
        });
        setPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setPriceActionPerformed(evt);
            }
        });

        config.setBackground(new java.awt.Color(0, 0, 0));
        config.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        config.setForeground(new java.awt.Color(255, 255, 255));
        config.setText("Configuration");
        config.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                configMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                configMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                configMouseExited(evt);
            }
        });
        config.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                configActionPerformed(evt);
            }
        });

        reports.setBackground(new java.awt.Color(0, 0, 0));
        reports.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        reports.setForeground(new java.awt.Color(255, 255, 255));
        reports.setText("Reports");
        reports.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reportsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                reportsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                reportsMouseExited(evt);
            }
        });
        reports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportsActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("<html><center>info@odexsoftware.com<br> Contact No. 03340693001</html>");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/odex-logo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(maintoShop, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(setPrice, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(config, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reports, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Main_Stock, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tPassEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FoodEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newDrinksCat, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(new_user, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {FoodEntry, Main_Stock, config, maintoShop, newDrinksCat, new_user, reports, setPrice, tPassEntry});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(new_user, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(newDrinksCat, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(FoodEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tPassEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(Main_Stock, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(maintoShop, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(setPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(config, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(reports, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(457, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {FoodEntry, Main_Stock, config, maintoShop, newDrinksCat, new_user, reports, setPrice, tPassEntry});

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel2.setText("Name");

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel6.setText("Phone No.");

        jLabel8.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel8.setText("Password");

        name.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N

        Phone_no.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N

        delete.setBackground(new java.awt.Color(255, 51, 0));
        delete.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        delete.setForeground(new java.awt.Color(255, 255, 255));
        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        update.setBackground(new java.awt.Color(255, 102, 102));
        update.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        update.setForeground(new java.awt.Color(255, 255, 255));
        update.setText("update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        add.setBackground(new java.awt.Color(0, 153, 51));
        add.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        add.setForeground(new java.awt.Color(255, 255, 255));
        add.setText("add");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 51, 255));
        jButton1.setText("clear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordActionPerformed(evt);
            }
        });

        UserDetalis.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "User Name", "Name", "Phone No.", "User Type"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        UserDetalis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UserDetalisMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(UserDetalis);

        jComboBox7.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrator", "Food Shop Manager", "Off Shop Manager", "On Shop Manager" }));
        jComboBox7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox7ActionPerformed(evt);
            }
        });

        jLabel62.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel62.setText("User Type");

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel3.setText("User Name");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane4))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel62, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(name)
                            .addComponent(Phone_no)
                            .addComponent(Password)
                            .addComponent(jComboBox7, 0, 320, Short.MAX_VALUE))
                        .addGap(92, 92, 92)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField39, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(update)))))
                .addContainerGap())
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {Password, Phone_no, jComboBox7, name});

        jPanel4Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel2, jLabel3, jLabel6, jLabel62, jLabel8});

        jPanel4Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {add, delete, jButton1, update});

        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField39, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Phone_no, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(add, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                            .addComponent(update, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(delete))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel62, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(33, 33, 33)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(16, 16, 16))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {Password, Phone_no, jComboBox7, jTextField39, name});

        jPanel4Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel2, jLabel3, jLabel6, jLabel62, jLabel8});

        jPanel4Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {add, delete, jButton1, update});

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 820, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(7, 7, 7))
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator2)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void new_userMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_new_userMouseEntered
        // TODO add your handling code here:
        new_user.setForeground(Color.red);
    }//GEN-LAST:event_new_userMouseEntered

    private void new_userMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_new_userMouseExited
        // TODO add your handling code here:
           new_user.setForeground(Color.white);
    }//GEN-LAST:event_new_userMouseExited

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
	
	//System.out.println(evt);
	UserDetalis.getSelectionModel().clearSelection();
	row = -1;
	jTextField39.setText("");
	jTextField39.setEditable(true);
	name.setText("");
	name.setEditable(true);
	Phone_no.setText("");
	Phone_no.setEditable(true);
	Password.setText("");
	Password.setEditable(true);
	jComboBox7.setSelectedItem(1);
	jComboBox7.setEnabled(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
	String si = String.valueOf(jComboBox7.getSelectedItem());
	int atype = 0;
	//System.out.println(si);
	switch(si)
            {
                case "Administrator":
                    atype = 1;
                    break; 
		case "Food Shop Manager":
                    atype = 2;
                    break;
		case "Off Shop Manager":
                    atype = 3;
                    break; 
		case "On Shop Manager":
                    atype = 4;
                    break;
	    }
	if(!jTextField39.getText().trim().equals("") && !Password.getText().trim().equals("") && !name.getText().trim().equals("") && !Phone_no.getText().trim().equals(""))
	{
	    try 
	    {
		Connection con = Db_connection.getConnection();
		PreparedStatement ps = con.prepareStatement("insert into user values(?,?,?,?,?)");
		ps.setString(1, jTextField39.getText().trim());
		ps.setString(2, Password.getText().trim());
		ps.setInt(3, atype);
		ps.setString(4, name.getText().trim());
		ps.setString(5, Phone_no.getText().trim());
		int r = ps.executeUpdate();
		if(r == 0)
		{
		    JOptionPane.showMessageDialog(null, "<html><center><h3>User Can not be inserted<br>User name must be unique<br>Please click update for modification</html>");
		}
		else
		{
		    DefaultTableModel model = null;
		    model = (DefaultTableModel) UserDetalis.getModel();
		    //System.out.println(model.getRowCount());
		    //model.createNewRow();
		    model.insertRow(model.getRowCount(), new Object[]{jTextField39.getText().trim(), name.getText().trim(), Phone_no.getText(), jComboBox7.getSelectedItem()});
		    UserDetalis.getSelectionModel().clearSelection();
		    row = -1;
		    jTextField39.setText("");
		    jTextField39.setEditable(true);
		    name.setText("");
		    name.setEditable(true);
		    Phone_no.setText("");
		    Phone_no.setEditable(true);
		    Password.setText("");
		    Password.setEditable(true);
		    jComboBox7.setSelectedItem(1);
		    jComboBox7.setEnabled(true);
		}
		ps.close();
		con.close();
	    } 
	    catch (SQLException | HeadlessException ex) 
	    {
		JOptionPane.showMessageDialog(null, "<html><center><h3>User Can not be inserted<br>User name must be unique<br>Please click update for modification</html>");
	    } 
	}
	else
	    JOptionPane.showMessageDialog(null, "<html><h3>Fields can not be empty</html>");
    }//GEN-LAST:event_addActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
	if (row == -1)
	{
	    JOptionPane.showMessageDialog(null, "<html><center><h3>Select a existing user for update</html>");
	    return;
	}
	//System.out.println(row);
	if(!Password.getText().trim().equals("") && !Phone_no.getText().trim().equals(""))
	{
	    try 
	    {
		Connection con = Db_connection.getConnection();
		PreparedStatement ps = con.prepareStatement("UPDATE user SET pwd=?, phno=? where uname = ?");
		ps.setString(1, Password.getText().trim());
		ps.setString(2, Phone_no.getText().trim());
		ps.setString(3, jTextField39.getText().trim());
		int r = ps.executeUpdate();
		if(r == 0)
		{
		    JOptionPane.showMessageDialog(null, "<html><center><h3>User does not exist</html>");
		}
		else
		{
		    DefaultTableModel model = null;
		    model = (DefaultTableModel) UserDetalis.getModel();
		    model.removeRow(row);
		    model.insertRow(row , new Object[]{jTextField39.getText().trim(), name.getText().trim(), Phone_no.getText(), jComboBox7.getSelectedItem()});
		    UserDetalis.getSelectionModel().clearSelection();
		    row = -1;
		    jTextField39.setText("");
		    jTextField39.setEditable(true);
		    name.setText("");
		    name.setEditable(true);
		    Phone_no.setText("");
		    Phone_no.setEditable(true);
		    Password.setText("");
		    Password.setEditable(true);
		    jComboBox7.setSelectedItem(1);
		    jComboBox7.setEnabled(true);
		}
		ps.close();
		con.close();
	    } 
	    catch (SQLException | HeadlessException ex) 
	    {
		JOptionPane.showMessageDialog(null, "<html><center><h3>User Can not be updated<br>Some Error Occourd</html>");
	    } 
	}
	else
	    JOptionPane.showMessageDialog(null, "<html><h3>Password Or Phone No Can Not Be Empty</html>");
    }//GEN-LAST:event_updateActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
	try {
	    if (row == -1)
	    {
		JOptionPane.showMessageDialog(null, "<html><center><h3>Select a existing user for delete</html>");
		return;
	    }
	    Connection con = Db_connection.getConnection();
	    PreparedStatement ps = con.prepareStatement("DELETE FROM user WHERE uname=?");
	    ps.setString(1, jTextField39.getText().trim());
	    int r = ps.executeUpdate();
	    if(r == 0)
	    {
		JOptionPane.showMessageDialog(null, "<html><center><h3>User Can not be deleted<br>Some Error Occourd</html>");
	    }
	    else
	    {
		DefaultTableModel model = null;
		model = (DefaultTableModel) UserDetalis.getModel();
		model.removeRow(row);
		UserDetalis.getSelectionModel().clearSelection();
		row = -1;
		jTextField39.setText("");
		jTextField39.setEditable(true);
		name.setText("");
		name.setEditable(true);
		Phone_no.setText("");
		Phone_no.setEditable(true);
		Password.setText("");
		Password.setEditable(true);
		jComboBox7.setSelectedItem(1);
		jComboBox7.setEnabled(true);
	    }
	} 
	catch (SQLException ex) 
	{
	    Logger.getLogger(AdminFrame.class.getName()).log(Level.SEVERE, null, ex);
	}
	
    }//GEN-LAST:event_deleteActionPerformed

    private void new_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_new_userActionPerformed
        jPanel4.setVisible(true);
        jPanel6.setVisible(false);
      //  jPanel11.setVisible(false);
      /*  jPanel7.setVisible(false); 
        jPanel8.setVisible(false);*/
    }//GEN-LAST:event_new_userActionPerformed

    private void Main_StockMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Main_StockMouseEntered
       Main_Stock.setForeground(Color.red);      
    }//GEN-LAST:event_Main_StockMouseEntered

    private void Main_StockMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Main_StockMouseExited
     
         Main_Stock.setForeground(Color.white);
       
       //  Dealer_info.setVisible(false);
       
    }//GEN-LAST:event_Main_StockMouseExited

    private void Main_StockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Main_StockActionPerformed
        // TODO add your handling code here:
      //  jPanel5.setVisible(true);
        jPanel4.setVisible(false);
      /*  jPanel11.setVisible(true);
        jPanel10.setVisible(true);
        wineDisplay.setVisible(false);
        WineStockPanel.setVisible(false);
         wineDisplay.setVisible(false);
         DealerInfoPanel.setVisible(false);
         offshopPanel.setVisible(false);
         OnshopPanel.setVisible(false);
         ProductBill.setVisible(false);*/
         
         
    }//GEN-LAST:event_Main_StockActionPerformed

    private void tPassEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tPassEntryActionPerformed
        TransportPassEntry tPE = new TransportPassEntry();
        //sD.setBackground(new Color(0,0,0,0));
        tPE.setSize(w-200,h);
        jPanel6.removeAll();
        jPanel6.add(tPE);
        tPE.setVisible(true);
        jPanel6.revalidate();
        jPanel6.repaint();
        jPanel4.setVisible(false);
        jPanel6.setVisible(true);
        tPE.jTextField1.requestFocus();
    }//GEN-LAST:event_tPassEntryActionPerformed

    private void tPassEntryMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tPassEntryMouseEntered
        // TODO add your handling code here:
          tPassEntry.setForeground(Color.red);
    }//GEN-LAST:event_tPassEntryMouseEntered

    private void tPassEntryMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tPassEntryMouseExited
        // TODO add your handling code here:
          tPassEntry.setForeground(Color.white);
    }//GEN-LAST:event_tPassEntryMouseExited
    int row = -1;
    private void UserDetalisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UserDetalisMouseClicked
	row=UserDetalis.getSelectedRow();
	if(row != -1)
	{
	    jTextField39.setText(UserDetalis.getModel().getValueAt(row,0).toString());
	    jTextField39.setEditable(false);
	    name.setText(UserDetalis.getModel().getValueAt(row,1).toString());
	    name.setEditable(false);
	    Phone_no.setText(UserDetalis.getModel().getValueAt(row,2).toString());
	    Password.setText("");
	    jComboBox7.setSelectedItem(UserDetalis.getModel().getValueAt(row,3));
	    jComboBox7.setEnabled(false);
	}
    }//GEN-LAST:event_UserDetalisMouseClicked

    private void PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordActionPerformed

    private void jComboBox7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox7ActionPerformed

    private void FoodEntryMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FoodEntryMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_FoodEntryMouseEntered

    private void FoodEntryMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FoodEntryMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_FoodEntryMouseExited
    FoodEntry fen=null;
    private void FoodEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FoodEntryActionPerformed
          jPanel4.setVisible(false);
       // jPanel11.setVisible(false);
        fen=new FoodEntry();
        //fen.setSize(w-292,h);
       //fen.setLocation(w,h);
        jPanel6.add(fen);//.setVisible(true);
        fen.setVisible(true);
        jPanel6.revalidate();
        jPanel6.setVisible(true);
        //ObjDao.fe=fe;
 
        
    }//GEN-LAST:event_FoodEntryActionPerformed

    private void newDrinksCatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newDrinksCatMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_newDrinksCatMouseEntered

    private void newDrinksCatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newDrinksCatMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_newDrinksCatMouseExited
    
    private void newDrinksCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newDrinksCatActionPerformed
        jPanel4.setVisible(false);
       // jPanel11.setVisible(false);
        NewDrinksCategory nDC = new NewDrinksCategory();
        nDC.setSize(w-200,h);
        jPanel6.removeAll();
        jPanel6.repaint();
        jPanel6.add(nDC);
        nDC.setVisible(true);
        jPanel6.setVisible(true);
        jPanel6.revalidate();
        nDC.kofl.requestFocus();
       
        // TODO add your handling code here:
    }//GEN-LAST:event_newDrinksCatActionPerformed

    private void newDrinksCatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newDrinksCatMouseClicked
        
        // TODO add your handling code here:
    }//GEN-LAST:event_newDrinksCatMouseClicked

    private void Main_StockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Main_StockMouseClicked
        // TODO add your handling code here:
      jPanel4.setVisible(false);
      MainStockEntry msk= new MainStockEntry();
      msk.setSize(w-200, h);
      jPanel6.removeAll();
        jPanel6.repaint();
        jPanel6.add(msk);
        msk.setVisible(true);
        jPanel6.setVisible(true);
        jPanel6.revalidate();
        msk.tpass.requestFocus();
      
    }//GEN-LAST:event_Main_StockMouseClicked

    private void FoodEntryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FoodEntryMouseClicked
        // TODO add your handling code here:
     jPanel4.setVisible(false);
     FoodEntry  nfe= new FoodEntry();
      nfe.setSize(w-200, h);
      jPanel6.removeAll();
        jPanel6.repaint();
        jPanel6.add(nfe);
        nfe.setVisible(true);
        jPanel6.setVisible(true);
        jPanel6.revalidate();
        nfe.ftype1.requestFocus();
          
        
    }//GEN-LAST:event_FoodEntryMouseClicked

    private void maintoShopMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maintoShopMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_maintoShopMouseEntered

    private void maintoShopMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maintoShopMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_maintoShopMouseExited

    private void maintoShopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maintoShopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maintoShopActionPerformed

    private void maintoShopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maintoShopMouseClicked
        // TODO add your handling code here:
        jPanel4.setVisible(false);
        WineDistribution wd= new WineDistribution();
        
        wd.setSize(w-200, h);
        jPanel6.removeAll();
        jPanel6.repaint();
        jPanel6.add(wd);
        wd.setVisible(true);
        jPanel6.setVisible(true);
        jPanel6.revalidate();
        wd.b1.requestFocus();
        
    }//GEN-LAST:event_maintoShopMouseClicked

    private void setPriceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_setPriceMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_setPriceMouseClicked

    private void setPriceMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_setPriceMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_setPriceMouseEntered

    private void setPriceMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_setPriceMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_setPriceMouseExited

    private void setPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setPriceActionPerformed
        jPanel4.setVisible(false);
        OnshopSetPrice oSP= new OnshopSetPrice();
        
        oSP.setSize(w-200, h);
        jPanel6.removeAll();
        jPanel6.repaint();
        jPanel6.add(oSP);
        oSP.setVisible(true);
        jPanel6.setVisible(true);
        jPanel6.revalidate();
        oSP.barcode.requestFocus();
        
        // TODO add your handling code here:
    }//GEN-LAST:event_setPriceActionPerformed

    private void configMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_configMouseClicked
        jPanel4.setVisible(false);
        Configuration cFG= new Configuration();
        
        cFG.setSize(w-200, h);
        jPanel6.removeAll();
        jPanel6.repaint();
        jPanel6.add(cFG);
        cFG.setVisible(true);
        jPanel6.setVisible(true);
        jPanel6.revalidate();
        cFG.vat.requestFocus();
        // TODO add your handling code here:
    }//GEN-LAST:event_configMouseClicked

    private void configMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_configMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_configMouseEntered

    private void configMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_configMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_configMouseExited

    private void configActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_configActionPerformed
        
        // TODO add your handling code here:
    }//GEN-LAST:event_configActionPerformed

    private void reportsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportsMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_reportsMouseClicked

    private void reportsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportsMouseEntered
        reportsPopUp.show(reports, reports.getWidth(), 0);
        // TODO add your handling code here:
    }//GEN-LAST:event_reportsMouseEntered

    private void reportsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportsMouseExited
        //reportsPopUp.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_reportsMouseExited

    private void reportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reportsActionPerformed

    private void tPassReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tPassReportsActionPerformed
        jPanel4.setVisible(false);
        TransportPassReport tPR= new TransportPassReport();
        
        tPR.setSize(w-200, h);
        jPanel6.removeAll();
        jPanel6.repaint();
        jPanel6.add(tPR);
        tPR.setVisible(true);
        jPanel6.setVisible(true);
        jPanel6.revalidate();
        tPR.today.requestFocus();
        // TODO add your handling code here:
    }//GEN-LAST:event_tPassReportsActionPerformed

    private void mainStockReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainStockReportsActionPerformed
        jPanel4.setVisible(false);
        MainStockReport mR= new MainStockReport();
        
        mR.setSize(w-200, h);
        jPanel6.removeAll();
        jPanel6.repaint();
        jPanel6.add(mR);
        mR.setVisible(true);
        jPanel6.setVisible(true);
        jPanel6.revalidate();
        mR.type.requestFocus();
        // TODO add your handling code here:
    }//GEN-LAST:event_mainStockReportsActionPerformed

    private void cashColReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashColReportsActionPerformed
        jPanel4.setVisible(false);
        CashCollectionRepot cCR= new CashCollectionRepot();
        
        cCR.setSize(w-200, h);
        jPanel6.removeAll();
        jPanel6.repaint();
        jPanel6.add(cCR);
        cCR.setVisible(true);
        jPanel6.setVisible(true);
        jPanel6.revalidate();
        cCR.type.requestFocus();

        // TODO add your handling code here:
    }//GEN-LAST:event_cashColReportsActionPerformed

    private void sellsReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sellsReportsActionPerformed
        jPanel4.setVisible(false);
        SellsReport sR= new SellsReport();
        
        sR.setSize(w-200, h);
        jPanel6.removeAll();
        jPanel6.repaint();
        jPanel6.add(sR);
        sR.setVisible(true);
        jPanel6.setVisible(true);
        jPanel6.revalidate();
        sR.type.requestFocus();
        // TODO add your handling code here:
    }//GEN-LAST:event_sellsReportsActionPerformed

    private void sellStockReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sellStockReportsActionPerformed
        jPanel4.setVisible(false);
        SellStockReport sSR= new SellStockReport();
        
        sSR.setSize(w-200, h);
        jPanel6.removeAll();
        jPanel6.repaint();
        jPanel6.add(sSR);
        sSR.setVisible(true);
        jPanel6.setVisible(true);
        jPanel6.revalidate();
        sSR.type.requestFocus();
        // TODO add your handling code here:
    }//GEN-LAST:event_sellStockReportsActionPerformed

    /**
     * @param args the command line arguments
     */
    /*public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
        /*
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form 
        java.awt.EventQueue.invokeLater(new RunnableImpl());
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton FoodEntry;
    private javax.swing.JButton Main_Stock;
    private javax.swing.JPasswordField Password;
    private javax.swing.JTextField Phone_no;
    private javax.swing.JTable UserDetalis;
    private javax.swing.JButton add;
    private javax.swing.JMenuItem cashColReports;
    private javax.swing.JButton config;
    private javax.swing.JButton delete;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JTextField jTextField39;
    private javax.swing.JMenuItem mainStockReports;
    private javax.swing.JButton maintoShop;
    private javax.swing.JTextField name;
    private javax.swing.JButton newDrinksCat;
    private javax.swing.JButton new_user;
    private javax.swing.JButton reports;
    private javax.swing.JPopupMenu reportsPopUp;
    private javax.swing.JMenuItem sellStockReports;
    private javax.swing.JMenuItem sellsReports;
    private javax.swing.JButton setPrice;
    private javax.swing.JButton tPassEntry;
    private javax.swing.JMenuItem tPassReports;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables

    /*private static class RunnableImpl implements Runnable {

	public RunnableImpl() {
	}

	@Override
	public void run()
	{
	    new AdminFrame().setVisible(true);
	}
    }*/
}
