/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package design;

import bean.Db_connection;
import bean.ObjDao;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Arka
 */
public class OnShop extends javax.swing.JFrame {

    /**
     * Creates new form OnShop1
     */
    int h, w;
    public OnShop() {
        ObjDao.OS = this;
        initComponents();
        
        Toolkit t = Toolkit.getDefaultToolkit();
        Dimension d = t.getScreenSize();
      /*  h = d.height;
        w = d.width;*/
      w=(int)t.getScreenSize().getWidth();
      h=(int)t.getScreenSize().getHeight();
       // ObjPass.w = w;
        //ObjPass.h = h;
        this.setSize( w, h );
        this.setExtendedState(java.awt.Frame.MAXIMIZED_BOTH);
     Table();
     addButton();
     AddFood();
        
    }
    
    public void Table() {
        try {
            Connection con = Db_connection.getConnection();
            PreparedStatement ps = con.prepareStatement("Select tableno from constant where slno='" + 1 + "'");
            ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                int i = rs.getInt("tableno");
                for (int m = 1; m <= i; m++) {
                    tableno.addItem("Table No-" + m);
                }
                //           
            }
            rs.close();
            ps.close();
            con.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    /*public void GetPanel()
    {
        aio= new AddItemOffShop();
        aio.setSize(w,hight1+10);
        hight1=hight1+80;
        System.out.println("Hight "+hight1);
        jPanel2.repaint(); 
        jScrollPane1.repaint();

        jPanel2.add(aio);
        aio.setVisible(true);
        jPanel2.revalidate();
        jScrollPane1.revalidate();
        System.out.println("2 "+ +ai o.getWidth() +" "+aio.getHeight());  
        cont1.add(new AddItemOffShop());
        
    }*/
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ptype = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tableno = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tBill = new javax.swing.JTextField();
        phno = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cash = new javax.swing.JRadioButton();
        online = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        dtBill = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        ftBill = new javax.swing.JTextField();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel49 = new javax.swing.JLabel();
        Quantity1 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        ok = new javax.swing.JButton();
        cal = new javax.swing.JButton();
        newBill = new javax.swing.JButton();
        jLabel51 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel6 = new javax.swing.JPanel();
        ok1 = new javax.swing.JButton();
        newBill1 = new javax.swing.JButton();
        cal1 = new javax.swing.JButton();
        Amount = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        Amount1 = new javax.swing.JLabel();
        Quantity = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();

        ptype.add(cash);
        ptype.add(online);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ON SHOP SELL");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel2.setText("Table No");

        tableno.setFont(new java.awt.Font("Verdana", 3, 14)); // NOI18N
        tableno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Select-" }));

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel3.setText("Customer Name");

        cname.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel4.setText("Ph No.");

        tBill.setEditable(false);
        tBill.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        tBill.setEnabled(false);

        phno.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel5.setText("Total Bill");

        cash.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        cash.setText("Cash");

        online.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        online.setText("Online");

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel6.setText("Total Drinks Bill");

        dtBill.setEditable(false);
        dtBill.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        dtBill.setEnabled(false);

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel7.setText("Total Food Bill");

        ftBill.setEditable(false);
        ftBill.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        ftBill.setEnabled(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tableno, 0, 218, Short.MAX_VALUE)
                            .addComponent(cname)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(phno)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tBill, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dtBill, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cash)
                            .addComponent(online)))
                    .addComponent(ftBill, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel2, jLabel3, jLabel4, jLabel5});

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cname, phno, tableno});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tableno, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tBill, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cash))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dtBill, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(online, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(phno, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ftBill, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cash, cname, dtBill, ftBill, jLabel2, jLabel3, jLabel4, jLabel5, jLabel6, jLabel7, online, phno, tBill, tableno});

        jLabel49.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel49.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel49.setText("Price(Rs.)");

        Quantity1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        Quantity1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Quantity1.setText("Quantity");

        jLabel47.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel47.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel47.setText("Peg(ML)");

        jLabel45.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel45.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel45.setText("Brand name");

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        ok.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ok.setText("OK");
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });

        cal.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cal.setText("Calculate");
        cal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calActionPerformed(evt);
            }
        });

        newBill.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        newBill.setText("New Bill");
        newBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newBillActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(1124, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ok, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newBill, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(ok, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cal, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(newBill, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1867, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel2);

        jLabel51.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel51.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel51.setText("Bar Code");

        jLabel53.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel53.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel53.setText("Category");

        jLabel54.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel54.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel54.setText("ML/Bottle");

        jLabel55.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel55.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel55.setText("Rate");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel51, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel53, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel54, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel47, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Quantity1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel55, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel49)
                .addContainerGap(315, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1258, Short.MAX_VALUE))
                .addGap(1, 1, 1))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel47, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel49)
                    .addComponent(Quantity1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel51, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel53, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel54, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel55))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {Quantity1, jLabel45, jLabel47, jLabel49, jLabel51, jLabel53, jLabel54, jLabel55});

        jTabbedPane1.addTab("<html><h3>Drinks</h3>", jPanel4);

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        ok1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ok1.setText("OK");
        ok1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ok1ActionPerformed(evt);
            }
        });

        newBill1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        newBill1.setText("New Bill");
        newBill1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newBill1ActionPerformed(evt);
            }
        });

        cal1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cal1.setText("Calculate");
        cal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cal1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(1125, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ok1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cal1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newBill1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(ok1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cal1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(newBill1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(2502, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(jPanel6);

        Amount.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        Amount.setText("Amount");

        jLabel44.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel44.setText("Category");

        Amount1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        Amount1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Amount1.setText("<html><center>Price<br>(RS)");

        Quantity.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        Quantity.setText("Quantity");

        jLabel48.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel48.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel48.setText("<html><center>Discount<br>(%)");

        jLabel56.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel56.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel56.setText("<html><center>Total<br>Price(Rs)");

        jLabel46.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel46.setText("Food Name");

        jLabel50.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel50.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel50.setText("<html><center>VAT");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(Quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(Amount1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Amount, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel50, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel48, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel56, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel56, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel48, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel50, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Amount, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Amount1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2))
                    .addComponent(Quantity, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("<html><h3>Food</html>", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(2, 2, 2))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed
        okClicked();
        // TODO add your handling code here:
    }//GEN-LAST:event_okActionPerformed

    private void calActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calActionPerformed
        calculate();
        // TODO add your handling code here:
    }//GEN-LAST:event_calActionPerformed

    private void newBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newBillActionPerformed
        new OnShop().setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_newBillActionPerformed

    private void ok1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ok1ActionPerformed
        okClicked();
        // TODO add your handling code here:
    }//GEN-LAST:event_ok1ActionPerformed

    private void cal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cal1ActionPerformed
        calculate();
        // TODO add your handling code here:
    }//GEN-LAST:event_cal1ActionPerformed

    private void newBill1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newBill1ActionPerformed
        new OnShop().setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_newBill1ActionPerformed

    /*
    public void addButton()
    {  
        AddItemOffShop aio= new AddItemOffShop();
        aio.setSize(w,hight1+65);
        hight1=hight1+65;
        //System.out.println("Hight "+hight1);
        jPanel2.repaint();
        jScrollPane1.repaint();

        jPanel2.add(aio);
        aio.setVisible(true);
        jPanel2.revalidate();
        jScrollPane1.revalidate();
        //System.out.println("21 "+ +aio.getWidth() +" "+aio.getHeight());  
        cont1.add(aio);
       // this.pack(); 

}*/
    
    
    
    
    public void addButton()
    {  
        AddItemOnShop aio= new AddItemOnShop();
        
        aio.setSize(w-150,60);
        aio.setLocation(0,hight1);
        //System.out.println(w+"Hight "+hight1);
        hight1=hight1+60;
        jPanel2.repaint();
        jScrollPane1.repaint();

        jPanel2.add(aio);
        aio.setVisible(true);
        jPanel2.revalidate();
        jScrollPane1.revalidate();
        aio.category.requestFocus();
        if(!cont1.isEmpty())
        {cont1.get(cont1.size() - 1).jLabel1.setVisible(false);
            cont1.get(cont1.size()-1).jLabel2.setVisible(false); 
        }
        //System.out.println("21 "+ +aio.getWidth() +" "+aio.getHeight());  
        cont1.add(aio);
       // this.pack(); 
       //System.out.println("0 "+cont1.size());  

}
    
    public void remove()
    {     if(cont1.size()>1)
          {
            hight1=hight1-60;
            cont1.get(cont1.size()-1).setVisible(false);
            cont1.remove(cont1.size()-1);
            //System.out.println("1 "+cont1.size());  
            
            cont1.get(cont1.size()-1).jLabel1.setVisible(true);  
            cont1.get(cont1.size()-1).jLabel2.setVisible(true); 
          }
    }             
    int  hight1=10;
    ArrayList <AddItemOnShop> cont1 = new ArrayList <AddItemOnShop>();
    /**
     * @param args the command line arguments
     */
    
    
     ArrayList <AddFoodItem > count2  = new ArrayList <AddFoodItem >();
     
    int  hight2=10;
    public void AddFood()
    {

        AddFoodItem  ob= new AddFoodItem ();
        ob.setSize(w-150,60);
        ob.setLocation(0,hight2);
        hight2=hight2+60;
        jPanel6.repaint();
        jScrollPane2.repaint();

        jPanel6.add(ob);
        ob.setVisible(true);
        jPanel6.revalidate();
        jScrollPane2.revalidate();
        ob.Ftype.requestFocus();
        if(!count2.isEmpty())
        {
         count2.get(count2.size() - 1).jLabel5.setVisible(false);
         count2.get(count2.size()-1).jLabel4.setVisible(false); 
        }
        //System.out.println("21 "+ +ob.getWidth() +" "+ob.getHeight());  
        count2.add(ob);
        
    }
    public void RemoveFood()
    {
      if(count2.size()>1)
          {
            hight2=hight2-60;
             count2.get( count2.size()-1).setVisible(false);
             count2.remove( count2.size()-1);
            //System.out.println("1 "+count2.size());  
            
             count2.get( count2.size()-1).jLabel4.setVisible(true);  
             count2.get( count2.size()-1).jLabel5.setVisible(true); 
          }   
    }
  
    public void calculate()
    {
        Double dtotal = 0.0;
        Double ftotal = 0.0;
        for(int i=0; i<cont1.size(); i++)
        {
            if(!cont1.get(i).barcode.getText().trim().equals("") && !cont1.get(i).brname.getSelectedItem().toString().trim().equals("")
                    && !cont1.get(i).qty.getText().trim().equals("") && !cont1.get(i).price.getText().trim().equals(""))
                           dtotal = dtotal + Double.parseDouble(cont1.get(i).price.getText().trim());
        }
        dtBill.setText(String.valueOf(new DecimalFormat("##.##").format(dtotal)));
        
        for (AddFoodItem each : count2) 
        {
            if (!each.Ftype.getSelectedItem().equals("-Select-") && !each.fname1.getSelectedItem().equals("-Select-")
                    && !each.qty2.getText().trim().equals("0") && !each.price.getText().trim().equals("00.00") && !each.vat1.getText().trim().equals("00.00")) 
            {
                ftotal = ftotal + Double.parseDouble(each.price.getText().trim());
            }
        }
        ftBill.setText(String.valueOf(new DecimalFormat("##.##").format(ftotal)));
        
        tBill.setText(String.valueOf(new DecimalFormat("##.##").format(dtotal+ftotal)));
    
    }
    
    public void okClicked()
   {
       calculate();
       if(!cname.getText().trim().equals("") && !tBill.getText().trim().equals("0"))
        {
           if(cash.isSelected())
            {
                onPtype = 1;
                OnPTNo tForm = new OnPTNo();
                this.setEnabled(false);
                this.setCursor(new Cursor(Cursor.WAIT_CURSOR));
                tForm.setVisible(true);
                tForm.tno.setText("@InCash");
                tForm.callOkMouse();
                //inSert();
            }
            else if(online.isSelected())
            {
                onPtype = 0;
                OnPTNo tForm = new OnPTNo();
                tForm.setVisible(true);
                this.setEnabled(false);
                this.setCursor(new Cursor(Cursor.WAIT_CURSOR));
                tForm.tno.requestFocus();
                //inSert();
            }
        }
   }
   
   int onPtype = 1;
   long billno = 0;

   public void inSert()
   {
       calculate();
       if(!cname.getText().trim().equals("") && !tBill.getText().trim().equals("") && !tableno.getSelectedItem().toString().trim().equals("-Select-"))
       {
           
           try {
               Connection con = Db_connection.getConnection();
               PreparedStatement ps = con.prepareStatement("insert into bill (name,phno,ptype,tno,bfrom,offamt,onamt,foamt,tableno,date) values (?,?,?,?,?,?,?,?,?,?)",Statement.RETURN_GENERATED_KEYS);
               ps.setString(1, cname.getText().trim());
               ps.setString(2, phno.getText().trim());
               ps.setInt(3, onPtype);
               ps.setString(4, ObjDao.onTno);
               ps.setInt(5,2);
               ps.setInt(6, 0);
               ps.setString(7, dtBill.getText().trim());
               ps.setString(8, ftBill.getText().trim());
               String trname = tableno.getSelectedItem().toString().trim();
               ps.setInt(9, Integer.parseInt(trname.substring(9, trname.length())));
               ps.setString(10, new SimpleDateFormat("yyyy-MM-dd").format(new Date()));
               ps.executeUpdate();
               ResultSet rs = ps.getGeneratedKeys();
               if(rs.next())
                   billno = rs.getLong(1);
               else
               {
                   JOptionPane.showMessageDialog(null, "<html>Bill No Can't Be Generated<br>Please Try Again</html>");
                   return;
               }
               rs.close();
               ps.close();
               
               for(AddItemOnShop each : cont1)
               {
                   if(!each.barcode.getText().trim().equals("") && !each.brname.getSelectedItem().toString().trim().equals("")
                            && (!each.qty.getText().trim().equals("0") || !each.qty.getText().trim().equals("")) && !each.price.getText().trim().equals("00.00") && !each.rate.getText().trim().equals("00.00"))
                   {
                        ps = con.prepareStatement("insert into onshopstock (date, dcode, qtyml, mlinstock, price30ml, ttype, billno) values (?,?,?,?,?,?,?)");
                        ps.setString(1, new SimpleDateFormat("yyyy-MM-dd").format(new Date()));
                        ps.setString(2, each.barcode.getText().trim());
                        int qtyml = 0;
                        if (each.peg.getSelectedItem().toString().trim().equals("60ML")) {
                            qtyml = Integer.parseInt(each.qty.getText()) * 2 * 30;
                        }
                        if (each.peg.getSelectedItem().toString().trim().equals("30ML")) {
                            qtyml = Integer.parseInt(each.qty.getText()) * 30;
                        }                        
                        ps.setInt(3, qtyml);
                        ps.setLong(4, each.instock);
                        ps.setDouble(5, Double.parseDouble(each.rate.getText().trim()));
                        ps.setInt(6, 0);
                        ps.setLong(7, billno);

                        int stat = ps.executeUpdate();
                        
                        if(stat == 0)
                            JOptionPane.showMessageDialog(null, "<html><center>Some Critical Error Occoured<br>Please Contact With DataBase Administrator</html>");
                   }
               }
               ps.close();
               con.close();
               
           } 
           catch (SQLException ex) 
           {
               Logger.getLogger(OnShop.class.getName()).log(Level.SEVERE, null, ex);
           }
           new OnShop().setVisible(true);
           this.dispose();
       }
   }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Amount;
    private javax.swing.JLabel Amount1;
    private javax.swing.JLabel Quantity;
    private javax.swing.JLabel Quantity1;
    private javax.swing.JButton cal;
    private javax.swing.JButton cal1;
    private javax.swing.JRadioButton cash;
    private javax.swing.JTextField cname;
    private javax.swing.JTextField dtBill;
    private javax.swing.JTextField ftBill;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton newBill;
    private javax.swing.JButton newBill1;
    private javax.swing.JButton ok;
    private javax.swing.JButton ok1;
    private javax.swing.JRadioButton online;
    private javax.swing.JTextField phno;
    private javax.swing.ButtonGroup ptype;
    private javax.swing.JTextField tBill;
    private javax.swing.JComboBox<String> tableno;
    // End of variables declaration//GEN-END:variables
}
