/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package design;

import bean.Db_connection;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author PC 4
 */
public class TransportPassEntry extends javax.swing.JPanel {

    /**
     * Creates new form TransportPassEntry
     */
    public TransportPassEntry() {
        initComponents();
        jDateChooser1.setDate(new Date());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel11 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jTextField35 = new javax.swing.JTextField();
        jLabel60 = new javax.swing.JLabel();
        jTextField36 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField37 = new javax.swing.JTextField();
        jLabel61 = new javax.swing.JLabel();
        jTextField38 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        top = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel1.setText("Transport Pass No");

        jTextField1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel2.setText("Date");

        jDateChooser1.setEnabled(false);
        jDateChooser1.setDateFormatString("dd-MM-yyyy");

        jLabel11.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel11.setText("<html>Requisition<br>No & Date</html>");

        jLabel59.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel59.setText("<html>Make of the Vehical<br> as specified in the<br> Registration Certificate <br>as Declared by<br>the applicant</html>");

        jTextField35.setEditable(false);
        jTextField35.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jTextField35.setText("N/A");
        jTextField35.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField35KeyPressed(evt);
            }
        });

        jLabel60.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel60.setText("<html>Model of the Vehical as specified in the Registration Certificate as Declared by the applicant</html>");

        jTextField36.setEditable(false);
        jTextField36.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jTextField36.setText("N/A");
        jTextField36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField36ActionPerformed(evt);
            }
        });
        jTextField36.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField36KeyPressed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel13.setText("<html>Motor Vehical Registration No. of the vehicle as specified in the registration certificate as declared by the applicant</html>");

        jTextField37.setEditable(false);
        jTextField37.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jTextField37.setText("N/A");
        jTextField37.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField37KeyPressed(evt);
            }
        });

        jLabel61.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel61.setText("<html>Invoice No. of the consignment to be Transported as declared by the consignor</html>");

        jTextField38.setEditable(false);
        jTextField38.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jTextField38.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField38KeyPressed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel12.setText("<html>Serial No Of<br>Transport<br>Pass</html>");

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextArea1KeyPressed(evt);
            }
        });
        jScrollPane3.setViewportView(jTextArea1);

        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane4.setAutoscrolls(true);

        jTextArea4.setEditable(false);
        jTextArea4.setColumns(20);
        jTextArea4.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jTextArea4.setLineWrap(true);
        jTextArea4.setRows(5);
        jTextArea4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextArea4KeyPressed(evt);
            }
        });
        jScrollPane4.setViewportView(jTextArea4);

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel3.setText("<html>Name of the<br>Consignor</html>");

        jTextField4.setEditable(false);
        jTextField4.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField4KeyPressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel4.setText("<html>Address of the<br>Consignor</html>");

        jScrollPane5.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jTextArea5.setEditable(false);
        jTextArea5.setColumns(20);
        jTextArea5.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jTextArea5.setLineWrap(true);
        jTextArea5.setRows(5);
        jTextArea5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextArea5KeyPressed(evt);
            }
        });
        jScrollPane5.setViewportView(jTextArea5);

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel5.setText("<html>Total Transaction Amount</html>");

        jTextField2.setEditable(false);
        jTextField2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jTextField2.setText("0");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButton3.setText("Update");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        top.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        top.setForeground(new java.awt.Color(255, 255, 255));
        top.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        top.setText("Transport Pass Entry");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(top, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(top, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel61, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField1)
                                    .addComponent(jTextField4)
                                    .addComponent(jTextField38)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 244, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60)))
                        .addGap(4, 4, 4)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(jLabel59, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                                    .addComponent(jLabel60, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                                    .addComponent(jTextField2)
                                    .addComponent(jTextField35)
                                    .addComponent(jTextField36)
                                    .addComponent(jTextField37)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel59, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel11))
                            .addComponent(jTextField35, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel60, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField36, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField37, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5)
                            .addComponent(jTextField2))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel61, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField38, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField36ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField36ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    int status = 0;
    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_DOWN || evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            jTextField1.setEditable(false);
            try 
            {
                Connection con = Db_connection.getConnection();
                PreparedStatement ps = con.prepareStatement("select * from dealer where tpassno = ?");
                ps.setString(1, jTextField1.getText().trim());
                ResultSet rs = ps.executeQuery();
                if(rs.next())
                {
                    status = 1;
                    System.out.println(rs.getString("date"));
                    jDateChooser1.setDate(new SimpleDateFormat("yyyy-MM-dd").parse(rs.getString("date")));
                    jTextArea1.setText(rs.getString("reqdate"));
                    jTextArea4.setText(rs.getString("tslno"));
                    jTextField4.setText(rs.getString("name_conr"));
                    jTextArea5.setText(rs.getString("add_conr"));
                    jTextField35.setText(rs.getString("make_vehicle"));
                    jTextField36.setText(rs.getString("model_vehicle"));
                    jTextField37.setText(rs.getString("reg_vehicle"));
                    jTextField38.setText(rs.getString("invoiceno"));
                    jTextField2.setText(String.valueOf(rs.getDouble("tamt")));
                    PreparedStatement psmain = con.prepareStatement("SELECT COUNT(tpassno) FROM mainstock");
                    ResultSet cnt = psmain.executeQuery();
                    cnt.next();
                    if(cnt.getLong(1) != 0)
                    {
                        JOptionPane.showMessageDialog(null, "<html><h3>Update Not Possible<br>Because "+cnt.getLong(1)+" Main Stock Entry Already Done</html>");
                    }
                    else
                    {
                        jTextArea1.setEditable(true);
                        jTextArea1.requestFocus();
                        jTextArea4.setEditable(true);
                        jTextField4.setEditable(true);
                        jTextArea5.setEditable(true);
                        jTextField35.setEditable(true);
                        jTextField36.setEditable(true);
                        jTextField37.setEditable(true);
                        jTextField38.setEditable(true);
                        jTextField2.setEditable(true);
                    }
                    cnt.close();
                    psmain.close();
                }
                else
                {
                    status = 0;
                    jTextArea1.setEditable(true);
                    jTextArea1.requestFocus();
                    jDateChooser1.setEnabled(true);
                    jTextArea4.setEditable(true);
                    jTextField4.setEditable(true);
                    jTextArea5.setEditable(true);
                    jTextField35.setEditable(true);
                    jTextField36.setEditable(true);
                    jTextField37.setEditable(true);
                    jTextField38.setEditable(true);
                    jTextField2.setEditable(true);
                }
                rs.close();
                ps.close();
                con.close();
                
            }
            catch (SQLException | ParseException ex) 
            {
                Logger.getLogger(TransportPassEntry.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_jTextField1KeyPressed

public static String formatDate (String givenDate, String givenFormat, String changeableFormat) throws ParseException 
{

    Date initDate = new SimpleDateFormat(givenFormat).parse(givenDate);
    SimpleDateFormat formatter = new SimpleDateFormat(changeableFormat);
    String changedDate = formatter.format(initDate);

    return changedDate;
}
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(status == 0)
            if(!jTextField1.getText().trim().equals("") && !jTextArea1.getText().trim().equals("")
                && !jTextArea4.getText().trim().equals("") && !jTextField4.getText().trim().equals("")
                && !jTextArea5.getText().trim().equals("") && !jTextField35.getText().trim().equals("")
                && !jTextField36.getText().trim().equals("") && !jTextField37.getText().trim().equals("")
                && !jTextField38.getText().trim().equals("") && !jTextField2.getText().trim().equals(""))

            {
            try 
            {
                Connection con = Db_connection.getConnection();
                PreparedStatement ps = con.prepareStatement("insert into dealer values(?,?,?,?,?,?,?,?,?,?,?)");
                ps.setString(1, jTextField1.getText().trim());
                //System.out.println(((JTextField)jDateChooser1.getDateEditor().getUiComponent()).getText());
                //ps.setString(2, (new SimpleDateFormat("yyyy-MM-dd").parse(((JTextField)jDateChooser1.getDateEditor().getUiComponent()).getText())).toString());
                ps.setString(2, formatDate(((JTextField)jDateChooser1.getDateEditor().getUiComponent()).getText(),"dd-MM-yyyy","yyyy-MM-dd"));               
                ps.setString(3, jTextArea1.getText());
                ps.setString(4, jTextArea4.getText());
                ps.setString(5, jTextField4.getText());
                ps.setString(6, jTextArea5.getText());
                ps.setString(7, jTextField35.getText());
                ps.setString(8, jTextField36.getText());
                ps.setString(9, jTextField37.getText());
                ps.setString(10, jTextField38.getText());
                ps.setDouble(11, Double.parseDouble(jTextField2.getText()));

                int rs = ps.executeUpdate();
                if(rs!= 0)
                {
                    JOptionPane.showMessageDialog(null, "<html><h3>Transport Pass Details Inserted Successfully</html>");
                }
                ps.close();
                con.close();
            }
            catch (SQLException | ParseException ex) 
            {
                //ex.printStackTrace();
                JOptionPane.showMessageDialog(null, "<html><h3>Some Error Occourd, Data Can Not Be Inserted</html>");
            }
            }
        else
                JOptionPane.showMessageDialog(null, "<html><h3>No Field Should Not Be Blank</html>");
        else
                JOptionPane.showMessageDialog(null, "<html><h3>Please Click On Update Button For Update</html>");
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jTextField1.setEditable(true);
        jTextField1.setText("");
        jTextField1.requestFocus();
        jTextArea1.setEditable(false);
        jTextArea1.setText("");
        jDateChooser1.setEnabled(false);
        jDateChooser1.setDate(new Date());
        jTextArea4.setEditable(false);
        jTextArea4.setText("");
        jTextField4.setEditable(false);
        jTextField4.setText("");
        jTextArea5.setEditable(false);
        jTextArea5.setText("");
        jTextField35.setEditable(false);
        jTextField35.setText("N/A");
        jTextField36.setEditable(false);
        jTextField36.setText("N/A");
        jTextField37.setEditable(false);
        jTextField37.setText("N/A");
        jTextField38.setEditable(false);
        jTextField38.setText("");
        jTextField2.setEditable(false);
        jTextField2.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextArea1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextArea1KeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_TAB || evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            jTextArea4.requestFocus();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextArea1KeyPressed

    private void jTextArea4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextArea4KeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_TAB || evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            jTextField4.requestFocus();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextArea4KeyPressed

    private void jTextField4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_TAB || evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            jTextArea5.requestFocus();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4KeyPressed

    private void jTextArea5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextArea5KeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_TAB || evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            jTextField38.requestFocus();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextArea5KeyPressed

    private void jTextField38KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField38KeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_TAB || evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            jTextField35.requestFocus();
        }        
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField38KeyPressed

    private void jTextField36KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField36KeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_TAB || evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            jTextField37.requestFocus();
        }        
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField36KeyPressed

    private void jTextField35KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField35KeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_TAB || evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            jTextField36.requestFocus();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField35KeyPressed

    private void jTextField37KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField37KeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_TAB || evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            jTextField2.requestFocus();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField37KeyPressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if(status == 1)
            if(!jTextField1.getText().trim().equals("") && !jTextArea1.getText().trim().equals("")
                && !jTextArea4.getText().trim().equals("") && !jTextField4.getText().trim().equals("")
                && !jTextArea5.getText().trim().equals("") && !jTextField35.getText().trim().equals("")
                && !jTextField36.getText().trim().equals("") && !jTextField37.getText().trim().equals("")
                && !jTextField38.getText().trim().equals("") && !jTextField2.getText().trim().equals(""))

            {
            try 
            {
                Connection con = Db_connection.getConnection();
                PreparedStatement ps = con.prepareStatement("update dealer set reqdate=?, tslno=?, name_conr=?, add_conr =?,"
                                                            + "make_vehicle=?, model_vehicle=?, reg_vehicle=?, invoiceno=?,"
                                                            + "tamt=? where tpassno = ?");
                //ps.setString(1, jTextField1.getText().trim());
                //System.out.println(((JTextField)jDateChooser1.getDateEditor().getUiComponent()).getText());
                //ps.setString(2, (new SimpleDateFormat("yyyy-MM-dd").parse(((JTextField)jDateChooser1.getDateEditor().getUiComponent()).getText())).toString());
                //ps.setString(2, formatDate(((JTextField)jDateChooser1.getDateEditor().getUiComponent()).getText(),"dd-MM-yyyy","yyyy-MM-dd"));               
                ps.setString(1, jTextArea1.getText());
                ps.setString(2, jTextArea4.getText());
                ps.setString(3, jTextField4.getText());
                ps.setString(4, jTextArea5.getText());
                ps.setString(5, jTextField35.getText());
                ps.setString(6, jTextField36.getText());
                ps.setString(7, jTextField37.getText());
                ps.setString(8, jTextField38.getText());
                ps.setDouble(9, Double.parseDouble(jTextField2.getText()));
                ps.setString(10, jTextField1.getText().trim());
                
                int rs = ps.executeUpdate();
                if(rs!= 0)
                {
                    JOptionPane.showMessageDialog(null, "<html><h3>Transport Pass Details Updated Successfully</html>");
                }
                ps.close();
                con.close();
            }
            catch (SQLException ex) 
            {
                //ex.printStackTrace();
                JOptionPane.showMessageDialog(null, "<html><h3>Some Error Occourd, Data Can Not Be Updated</html>");
            }
            }
        else
                JOptionPane.showMessageDialog(null, "<html><h3>No Field Should Not Be Blank</html>");
        else
                JOptionPane.showMessageDialog(null, "<html><h3>Please Click On Submit Button For Insert</html>");
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextArea jTextArea5;
    public javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField35;
    private javax.swing.JTextField jTextField36;
    private javax.swing.JTextField jTextField37;
    private javax.swing.JTextField jTextField38;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JLabel top;
    // End of variables declaration//GEN-END:variables
}
